env:
  PORT: 5600
  ROOT_URL: http://127.0.0.1:5600/
datasources:
  default:
    connection:
      host: 127.0.0.1
      database: steedos
    objectFiles:
      - "./src/**/"
  mailcow:
    connection:
      driver: mysql
      host: 192.168.0.33
      port: 13306
      username: mailcow
      password: 
      database: mailcow
    objectFiles:
      - "./mailcow/**/"
    appFiles:
      - "./mailcow/mailcow.app.yml"
public:
  webservices:
    mailcow: 
      url: ${MAILCOW_URL}
      initial_passwd: ${MAILCOW_INITIAL_PASSWD}
cfs:
  store: "local"
  local:
    folder: "./storage"
