env:
  PORT: 5600
datasources:
  default:
    connection: 
      host: 127.0.0.1
      database: steedos
  mailcow:
    connection: 
      driver: mysql
      host: 192.168.0.33
      port: 13306
      username: mailcow
      password: kSwR8tkHWwPYaMpv06faAw6rNYBP
      database: mailcow
    objectFiles: 
      - "./mailcow/"
    appFiles:
      - "./mailcow/mailcow.app.yml"
cfs:
  store: "local"
  local: 
    folder: "./storage"